Repository acmestack/godkits, pull requests merged in 2022-07, with the labels that each got.

#93 [type:feat] add id utils
  core/idutil.go
  core/idutil_test.go
  go.mod
  go.sum
Labels: enhancement

#98 [type:feat] support xlist
  gox/containerx/xlist/list.go
  gox/containerx/xlist/simple_list.go
  gox/containerx/xlist/simple_list_test.go
Labels: enhancement

#103 [type:feat] support snowflake.
  core/lang/snowflake.go
  core/lang/snowflake_test.go
Labels: enhancement

#104 feat:Add ascii85 coding tool class and test class
  gox/encodingx/ascii85x/ascii85x.go
  gox/encodingx/ascii85x/ascii85x_test.go
Labels: good first issue

#106 [type:feat] support os.
  core/system/os.go
  core/system/os_test.go
Labels: enhancement

#107 [type:feature] Add xmlx.go and xmlx_test.go
  gox/encodingx/xmlx/xmlx.go
  gox/encodingx/xmlx/xmlx_test.go
Labels: enhancement, good first issue
