Repository acmestack/godkits, pull requests merged in 2022-06, with the labels that each got.

#75 refactor: update readme doc
  README.md
Labels: documentation

#81 feat: bytes kits
  gox/bytesx/bytesx.go
  gox/bytesx/bytesx_test.go
Labels: enhancement, good first issue

#84 [type:feat] support assert.
  assert/assert.go
  assert/assert_test.go
Labels: good first issue

#85 [type:feat] add log module
  log/async_bufwriter.go
  log/async_writer.go
  log/log.go
  log/log_test.go
Labels: enhancement

#86 [type:fix] Reduced from go 1.18 to go 1.16
  array/array.go
  go.mod
  gox/containerx/listx/listx.go
  gox/cryptox/aesx/aesx_test.go
  gox/encodingx/base64x/base64x_test.go
  gox/encodingx/jsonx/jsonx.go
  gox/errorsx/errorsx_test.go
  gox/mapx/map_check.go
Labels: wontfix

#87 [type:fix] Update README.md
  README.md
Labels: documentation

#90 [type:feat] support xmap and lru. (acmestack#76)
  gox/containerx/lru/lru.go
  gox/containerx/lru/lru_test.go
  gox/containerx/lru/queue.go
  gox/containerx/lru/queue_test.go
  gox/containerx/xmap/linked_map.go
  gox/containerx/xmap/linked_map_test.go
  gox/containerx/xmap/map.go
  gox/containerx/xmap/simple_map.go
  gox/containerx/xmap/simple_map_test.go
Labels: enhancement
