Repository acmestack/godkits, pull requests merged in 2022-05, with the labels that each got.

#16 add issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: help wanted

#40 refactor: add license
  gox/md5x/md5x_test.go
Labels: enhancement

#45 refactor: md5x move to cryptorx
  README.md
  gox/cryptox/md5x/md5x.go
  gox/cryptox/md5x/md5x_test.go
Labels: invalid

#49 test: cover more stringsx
  gox/stringsx/stringsx_test.go
Labels: enhancement

#61 feat: add ForEach to Listx
  gox/containerx/listx/listx.go
  gox/containerx/listx/listx_test.go
Labels: enhancement, good first issue

#66 cla signatures to current repo
  .github/workflows/cla.yaml
Labels: enhancement

#73 [type:feat] commit base32x.go and base32x_test.go
  gox/encodingx/base32x/base32x.go
  gox/encodingx/base32x/base32x_test.go
Labels: enhancement, good first issue
